export enum ETaskStatuses {
    INITIAL_REVIEW = 'INITIAL_REVIEW',
    TRANSLATION = 'TRANSLATION',
    CAPTIONING = 'CAPTIONING',
    APPROVAL = 'APPROVAL',
    PUBLISHED = 'PUBLISHED',
    ARCHIVED = 'ARCHIVED',
}
